uav_ros_control: uav_controller Namespace Reference
uav_controller Namespace Reference
Data Structures
class CascadePID
class ControlBase
Functions
void runDefault (uav_controller::CascadePID &cc, ros::NodeHandle &nh)
Default position control program for Ardupilot firmware Uses roll, pitch, yaw, thrust Attitude Commands Roll and pitch are expressed in UAV body frame.
void runDefault_yawrate (uav_controller::CascadePID &cc, ros::NodeHandle &nh)
Default position control program for Ardupilot firmware Uses roll, pitch, yawrate, thrust Attitude Commands Roll and pitch are expressed in UAV body frame.
void runDefault_px4 (uav_controller::CascadePID &cascadeObj, ros::NodeHandle &nh)
Default position control program for PX4 firmware Uses roll, pitch, yaw, thrust Attitude Commands Roll and pitch are expressed in UAV body frame.
void runDefault_yawrate_px4 (uav_controller::CascadePID &cascadeObj, ros::NodeHandle &nh)
Default position control program for PX4 firmware Uses roll, pitch, yawrate, thrust Attitude Commands Roll and pitch are expressed in Odometry frame (That's ENU frame if using mavros/global_position/local)
Variables
const int MASK_IGNORE_RPY_RATE = 7
const int MASK_IGNORE_RP_RATE = 3
Function Documentation
void uav_controller::runDefault (uav_controller::CascadePID & cc, ros::NodeHandle & nh)
Default position control program for Ardupilot firmware Uses roll, pitch, yaw, thrust Attitude Commands Roll and pitch are expressed in UAV body frame.
Definition at line 308 of file CascadePID.cpp.
References uav_controller::CascadePID::activationPermission(), uav_controller::CascadePID::calculateAttThrustSp(), MASK_IGNORE_RPY_RATE, uav_controller::ControlBase::publishAttitudeTarget(), and uav_controller::ControlBase::publishEulerSp().
Referenced by main().
 {
   double rate = 50;
   double dt = 1.0 / rate;
   ros::Rate loopRate(rate);
   ROS_WARN_ONCE("[uav_controller::runDefault]: Control node for Ardupilot firmware is active!");
   while (ros::ok()) {
     ros::spinOnce();
     if (cascadeObj.activationPermission()) {
       cascadeObj.calculateAttThrustSp(dt);
       cascadeObj.publishAttitudeTarget(MASK_IGNORE_RPY_RATE);
     } else {
       ROS_FATAL_THROTTLE(2, "CascadePID::runDefault - controller inactive");
     }
     cascadeObj.publishEulerSp();
     loopRate.sleep();
   }
 }
void uav_controller::runDefault_px4 (uav_controller::CascadePID & cascadeObj, ros::NodeHandle & nh)
Default position control program for PX4 firmware Uses roll, pitch, yaw, thrust Attitude Commands Roll and pitch are expressed in UAV body frame.
Definition at line 329 of file CascadePID.cpp.
References uav_controller::CascadePID::calculateAttThrustSp(), MASK_IGNORE_RPY_RATE, uav_controller::ControlBase::publishAttitudeTarget(), and uav_controller::ControlBase::publishEulerSp().
Referenced by main().
 {
   double rate = 50;
   double dt = 1.0 / rate;
   ros::Rate loopRate(rate);
   ROS_WARN_ONCE("[uav_controller::runDefault_px4]: Control node for PX4 firmware is active!");
   while (ros::ok()) {
     ros::spinOnce();
     cascadeObj.calculateAttThrustSp(dt);
     cascadeObj.publishAttitudeTarget(MASK_IGNORE_RPY_RATE);
     cascadeObj.publishEulerSp();
     loopRate.sleep();
   }
 }
void uav_controller::runDefault_yawrate (uav_controller::CascadePID & cc, ros::NodeHandle & nh)
Default position control program for Ardupilot firmware Uses roll, pitch, yawrate, thrust Attitude Commands Roll and pitch are expressed in UAV body frame.
Definition at line 346 of file CascadePID.cpp.
References uav_controller::CascadePID::activationPermission(), uav_controller::CascadePID::calculateAttThrustSp(), uav_controller::CascadePID::calculateYawRateSetpoint(), MASK_IGNORE_RP_RATE, uav_controller::ControlBase::overrideYawTarget(), uav_controller::ControlBase::publishAttitudeTarget(), and uav_controller::ControlBase::publishEulerSp().
Referenced by main().
 {
   double rate = 50;
   double dt = 1.0 / rate;
   ros::Rate loopRate(rate);
   ROS_WARN_ONCE("[uav_controller::runDefault_yawrate]: Control node for Ardupilot firmware is active!");
   while (ros::ok()) {
     ros::spinOnce();
     if (cascadeObj.activationPermission()) {
       cascadeObj.calculateAttThrustSp(dt);
       cascadeObj.overrideYawTarget(0);
       const auto yawRateSetpoint = cascadeObj.calculateYawRateSetpoint(dt);
       cascadeObj.publishAttitudeTarget(MASK_IGNORE_RP_RATE, yawRateSetpoint);
     } else {
       ROS_FATAL_THROTTLE(2, "CascadePID::runDefault - controller inactive");
     }
     cascadeObj.publishEulerSp();
     loopRate.sleep();
   }
 }
void uav_controller::runDefault_yawrate_px4 (uav_controller::CascadePID & cascadeObj, ros::NodeHandle & nh)
Default position control program for PX4 firmware Uses roll, pitch, yawrate, thrust Attitude Commands Roll and pitch are expressed in Odometry frame (That's ENU frame if using mavros/global_position/local)
Definition at line 369 of file CascadePID.cpp.
References uav_controller::CascadePID::calculateAttThrustSp(), uav_controller::CascadePID::calculateYawRateSetpoint(), MASK_IGNORE_RP_RATE, uav_controller::ControlBase::publishAttitudeTarget(), and uav_controller::ControlBase::publishEulerSp().
Referenced by main().
 {
   double rate = 50;
   double dt = 1.0 / rate;
   ros::Rate loopRate(rate);
   bool yaw_rate_control_enabled = true;
   ROS_WARN_ONCE("[uav_controller::runDefault_yawrate_px4]: Control node for PX4 firmware is active!");
   while (ros::ok()) {
     ros::spinOnce();
     cascadeObj.calculateAttThrustSp(dt, yaw_rate_control_enabled);
     const auto yawRateSetpoint = cascadeObj.calculateYawRateSetpoint(dt);
     cascadeObj.publishAttitudeTarget(MASK_IGNORE_RP_RATE, yawRateSetpoint);
     cascadeObj.publishEulerSp();
     loopRate.sleep();
   }
 }
Variable Documentation
const int uav_controller::MASK_IGNORE_RP_RATE = 3
Type mask used when publishing AttitudeTarget ROS messages. It will ignore body roll and pitch rate values.
Definition at line 21 of file ControlBase.hpp.
Referenced by dist_control::runDefault(), runDefault_yawrate(), and runDefault_yawrate_px4().
const int uav_controller::MASK_IGNORE_RPY_RATE = 7
Type mask used when publishing AttitudeTarget ROS messages. It will ignore body roll, pitch and rate values.
Definition at line 17 of file ControlBase.hpp.
Referenced by runDefault(), and runDefault_px4().